import Logo from "./_components/Logo";
import Navigation from "./_components/navigation";
import "@/app/_styles/globals.css";
export const metadata = {
  title: "The Wild Oasis",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-primary-950 min-h-svh text-primary-50">
        <header>
          <Logo />
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  );
}
